
export const fatcaResponse = {
  "fetchCustAccResponse": {
    "customerDetailsDTO": [
      {
        "customerFullName": "roshan narendra sabale",
        "txtPermadrAdd1": "LOTUS HERBALS LTD",
        "rmPhoneNo": "617507998688",
        "codBlockReason": null,
        "namPermadrState": "GOA",
        "refOfficePhoneArea": "0",
        "refResPhoneArea": "0",
        "rmEmailID": null,
        "codMisCompCode1": "700",
        "memoSevrity": "N",
        "codRM": null,
        "prefCustFlag": "N",
        "codCustNatlId": "150125S9343002",
        "rmBranchName": null,
        "txtContryUltRisk": null,
        "namCustadrState": "GOA",
        "namCustadrCntryDescription": "IN",
        "flgCustMemo": "N",
        "keyPartnerCode": null,
        "customerAccountDetailsDTO": [
          {
            "prodFrqChqThresholdLim": 6,
            "flagATM": 15,
            "flgPos": "Y",
            "flagSWPOut": "N",
            "productcodProdType": "N",
            "ctrThreshholdDayLimit": 50,
            "productName": "SAVINGS - NRE",
            "flgNomineeNameDisplay": null,
            "nomineeAge": 0,
            "amtAqb4": null,
            "flgTbs": "Y",
            "amtAqb2": null,
            "amtAqb3": null,
            "accountOperatingInstructions": "Single",
            "amtAqb1": null,
            "amtAmb2": null,
            "amtAmb3": null,
            "amtAmb1": null,
            "flgChqGrntyFac": "N",
            "flgAtmFac": 15,
            "ctrChqThreshholdLimit": 50,
            "balBook": 0,
            "flgSiFac": "Y",
            "namGuardian": null,
            "branchCode": 2373,
            "flgOdFac": "Y",
            "customerShortName": "ROBERT",
            "prodChqThresholdDayLim": 50,
            "codTypProd": "A",
            "codProdType": 1,
            "prodCtrChqThresholdLim": 50,
            "codRel": 0,
            "micrCode": "999240713",
            "activationDate": "2025-01-15",
            "txtAcctMemo": "Caution!!!  NEW ACCOUNT",
            "frqChqThreshholdLimit": 6,
            "prodTypeDesc": "SAVING",
            "accountTitle": "roshan narendra sabale",
            "txtMsgAdv": "SAVINGS - NRE",
            "flgAtm": 15,
            "flgNet": "Y",
            "accountStatusDescription": "Regular",
            "availableBalance": 0,
            "codAcctNoExt": null,
            "accountStatus": 8,
            "flgChqbkFac": "Y",
            "unclearAmount": 0,
            "customerId": 901094430,
            "productTypeDescription": "NRE",
            "nomineeDOB": null,
            "ctrSrlNo": 1,
            "flgSwpinFac": "Y",
            "ifscCode": "HDFC0002373",
            "productType": "N",
            "flgSweepin": "N",
            "flgTPP": "N",
            "flgSeverity": "L",
            "amtHold": 0,
            "amountODLimit": 0,
            "flagMemo": "A",
            "netBalance": 0,
            "branchName": "MEMARI ANKAR-SUNDER NIWAS-HOSHIARP ",
            "nomineeName": null,
            "accountLongTitle": "roshan narendra sabale",
            "accountNumber": "50100117420333",
            "custExtNo": "901094430",
            "datAcctOpen": "20250115",
            "serviceBrnCode": 2373,
            "flagSI": "N",
            "productCode": 106,
            "flgSwpoutFac": "Y",
            "nomineeNam": null,
            "codAcctCustRel": "SOW",
            "currencyCode": 1,
            "prodcodCcy": 1
          }
        ],
        "mastCodGroupId": null,
        "codCustMarstat": 2,
        "refHoldTelex": null,
        "codBusinessCat": 0,
        "customerFirstName": null,
        "refCustPhoneOff": null,
        "flgDocComplete": "N",
        "status": {},
        "datIncorporated": null,
        "codBusinessRegno": null,
        "genderDescription": "Male",
        "namCustadrCntry": "IN",
        "kycStatus": "Y",
        "codCustIntroducerId": 0,
        "refHoldPhone": null,
        "txtEthnicOrigin": "0  ",
        "refOfficePhoneExtn": "0",
        "codGroup": null,
        "txtCustDesgn": null,
        "codTds": 203,
        "customerAMLDetailsDTO": [
          {
            "selfEmpFrom": null,
            "amlNum9": null,
            "amlNum8": null,
            "amlNum7": null,
            "amlNum6": null,
            "natIndCode": null,
            "incSrcDesc": "Salary",
            "iecCode": null,
            "datOfIncorp": null,
            "ausInCa": null,
            "amlNum1": null,
            "typeDocument": null,
            "annualTurnover": 0,
            "amlNum5": null,
            "amlNum4": null,
            "amlNum3": null,
            "amlNum2": null,
            "namCcy": "USD",
            "codProfession": null,
            "typEmployer": "2",
            "landHoldingInAcres": null,
            "amlDate10": null,
            "dtlActivity": null,
            "txtOccupDesc": "Salaried",
            "natIndDesc": null,
            "natureOfBus": null,
            "txtResDesc": "Owned",
            "docIssDate": null,
            "designation": null,
            "amlCod10": null,
            "codOccupation": "2",
            "subCatCode": null,
            "riskProfile": "LOW",
            "txtEmployerDesc": "Private Limited",
            "txtProfessionDesc": null,
            "datCashProfileExpiry": null,
            "docIssPlace": null,
            "grossIncome": "2",
            "amlCod6": null,
            "amlCod7": null,
            "amlCod4": null,
            "amlCod5": null,
            "amlCod2": null,
            "ausDate": null,
            "amlCod3": null,
            "grossIncDesc": "50,000 - 1,00,000",
            "amlCod1": "N",
            "typeOfBusiness": null,
            "txtCompanyDesc": null,
            "amlNum10": null,
            "subCatDesc": null,
            "txtDocumentDesc": null,
            "amlCod8": null,
            "amlCod9": "19",
            "typCompany": null,
            "amlDate1": "20250115",
            "amlDate2": "20250115",
            "amlDate3": "20250115",
            "amlDate4": null,
            "amlDate5": null,
            "amlDate6": null,
            "amlDate7": null,
            "documentId": "1",
            "amlDate8": null,
            "incomeSource": "2",
            "txtBusDesc": null,
            "amlDate9": "20250115",
            "typResidence": "2",
            "eximValue": null
          }
        ],
        "txtCustSex": "M",
        "customerId": 901094430,
        "datVerified": null,
        "memoNo": "0",
        "customerLastName": null,
        "txtCustadrAdd2": "8-9 SECTOR 58",
        "maritalStatusDescription": "Married",
        "txtCustadrAdd1": "LOTUS HERBALS LTD",
        "custHomeBranchCode": 2373,
        "txtCustadrAdd3": "CLARK AMER",
        "refPhoneMobile": "617507998688",
        "rmCode": null,
        "namMotherMaiden": "Julia",
        "namHoldadrCntry": "INDIA",
        "refResPhoneCountry": "0",
        "namPermadrCntryDescription": "AU",
        "refCustFax": null,
        "txtCustPrefix": "MR",
        "refCustItNum": "SOXCX1577E",
        "txtCustNATNLTY": "IN",
        "namPermadrCntry": "AU",
        "namDirector2": null,
        "namHoldadrCity": "CITY MEMARI, TESTING MAX CHARACTERS",
        "txtHoldadrAdd3": "NEW BUS STAND, ROAD NO 3",
        "refHoldFax": null,
        "datBirthCust": "20000101",
        "txtHoldadrAdd1": "HDFC BANK LTD, ROAD NO 1",
        "memoText": null,
        "refCustEmail": "ACADEA@DEDEE.com",
        "txtHoldadrAdd2": "HOLDING NO 12, ROAD NO 2",
        "ethnicCode": "0  ",
        "flgKio": "N",
        "customerFATCADtlsDTO": [
          {
            "txtLglCase": null,
            "ctrYrsJob": 0,
            "datVisaExpiry": null,
            "refCustEmpPhoneCountry": null,
            "addrTaxReporting1": "P",
            "addrTaxReporting2": null,
            "addrTaxReporting3": null,
            "txtMedIns": null,
            "namEmpadrCity": null,
            "refCustEmpEmail": null,
            "refCustEmpFax": null,
            "amtValHouse": 0,
            "txtAddr3SpoEmp": null,
            "refCustEmpFaxArea": null,
            "addrProof": "A",
            "addrTaxReporting4": null,
            "addrTaxReporting5": null,
            "namCustEmp": null,
            "txtDesgnPrevjob": null,
            "txtEmpadrAdd2": null,
            "txtEmpadrAdd3": null,
            "txtEmpadrAdd1": null,
            "namCityBirth": "Hyderabad",
            "datPsptIssue": null,
            "datExpiryVisa": null,
            "codCntryBirth": "IN",
            "addrTyp": 3,
            "ctrAgeRetire": 0,
            "typAddrTax5": null,
            "typAddrTax3": null,
            "namEmpadrCntry": null,
            "typAddrTax4": null,
            "txtSpoDesgn": null,
            "idDocExpDat": "20251020",
            "typAddrTax1": "3",
            "typAddrTax2": null,
            "txtMortAssts": null,
            "datFromPrevjob": null,
            "txtEmpDesignation": "manger",
            "txtTenrOccuptn": 0,
            "txtTypVisa": null,
            "codTaxCntry5": null,
            "idDocDesc": null,
            "refSpoEmpPhone": null,
            "datPsptExpiry": null,
            "namCustMaiden": null,
            "amtRentExp": 0,
            "txtEmpadrZip": null,
            "txtRsnLeftJob": null,
            "flgLglCase": "N",
            "codTaxCntry1": "AU",
            "codCcBrn": 2373,
            "codTaxCntry2": null,
            "codTaxCntry3": null,
            "codTaxCntry4": null,
            "namEmpadrState": null,
            "namEmp": "rupesh",
            "datToPrevjob": null,
            "namCustSpouse": null,
            "amtCustIncome": 0,
            "txtDesignation": null,
            "txtCrRating": "0",
            "namCrCard1": null,
            "namCrCard2": null,
            "namCrCard3": null,
            "namPrevEmp": null,
            "amtInsuExp": 0,
            "datAnnexure": "20250124",
            "txtOccuptnCat": 0,
            "datDobSpouse": null,
            "namSpoEmployer": null,
            "txtAddr1SpoEmp": null,
            "amtOthExpense": 0,
            "datMarriage": null,
            "flgTaxCntryCitizen4": null,
            "flgTaxCntryCitizen5": null,
            "flgTaxCntryCitizen2": null,
            "flgTaxCntryCitizen3": null,
            "amtOthIncome": 0,
            "idDocTyp": "A",
            "refCustEmpPhoneExtn": null,
            "datProcess": "20250124",
            "flgTaxCntryCitizen1": "N",
            "idDocNum": "ABV00001",
            "datCrRating": null,
            "refCustEmpMobile": null,
            "txtPoliceRecrd": null,
            "txtAddrProofDesc": "Passport No.",
            "namCustFather": "narendra",
            "txtCustOccuptn": null,
            "txtAddr2SpoEmp": null,
            "namSpouseCust": null,
            "refCustEmpFaxCountry": null,
            "txtRemarks": null,
            "refCrCard1": null,
            "txtValMort": null,
            "flgTaxCntryRes3": null,
            "refVisa": null,
            "refCustEmpPhoneArea": null,
            "flgTaxCntryRes2": null,
            "flgTaxCntryRes5": null,
            "flgTaxCntryRes4": null,
            "tinNo2": null,
            "tinNo3": null,
            "tinNo4": null,
            "tinNo5": null,
            "refCustEmpTelex": null,
            "typTinNo3": null,
            "typTinNo4": null,
            "typTinNo5": null,
            "tinNo1": "226781812",
            "ctrDurtnStay": null,
            "txtMedHist": null,
            "flgTaxCntryRes1": "N",
            "typTinNo1": "TAXPANFLUX",
            "typTinNo2": null,
            "codResStat": "A",
            "codEmpId": "R27141",
            "amtLastSal": 0,
            "refCustPspt": null,
            "refCustEmpPhone": null,
            "refCrCard3": null,
            "refCrCard2": null,
            "ctrUpdatSrlno": 2,
            "codNatlIdSpouse": null,
            "codVisaTyp": null,
            "txtOccpnSpouse": 0
          }
        ],
        "namCntryIncorp": null,
        "namCustadrCity": "PANAJI",
        "codCustStatus": 8,
        "panStatus": "Operative",
        "customerTypeDescription": "NON RESIDENT INDIAN",
        "customerBand": null,
        "addressChangeFlag": "18000101",
        "namHoldadrState": "WEST BENGAL",
        "flgStaff": "N",
        "txtCustResidence": "AU",
        "rmBranchCode": 0,
        "oldCustomerID": null,
        "txtPermadrZip": "2000",
        "refCustTelex": "8983278327",
        "customerShortName": "ROBERT",
        "flgVerifiedStat": "Y",
        "flgCustTyp": "O  ",
        "codUtlComp": "0004",
        "txtBusinessTyp": null,
        "txtHoldadrZip": "713146",
        "datAdhrLnkdAcctUpd": null,
        "rmName": null,
        "customerMiddleName": null,
        "codMisCustCode1": null,
        "txtContryInitRisk": "AU",
        "codEmployeeId": null,
        "codGroupId": null,
        "codAadhaarNo": null,
        "flgMinor": "N",
        "codStmtDispatchMode": "E",
        "cifType": "C",
        "refOfficePhoneCountry": "0",
        "datAadhaarUpdatedOn": null,
        "flgBlocked": "N",
        "refCustPhone": null,
        "txtCustadrZip": "403705",
        "refResPhoneExtn": "0",
        "ethnicCodeDesc": "OTHER 12",
        "refHoldEmail": null,
        "namPermadrCity": "ASMARA",
        "codLiabNo": null,
        "codAadhaarLinkAcct": null,
        "txtPermadrAdd2": "8-9 SECTOR 58",
        "txtPermadrAdd3": "CLARK AMER",
        "refHoldPhoneOff": null,
        "flgIcTyp": "I"
      }
    ],
    "Id_token_jwt": "D5a6fR7PtedHy-XKmF4bm4v6Bw5iCkPudnFLmUYaCXfz8zc7-hu46Mn1y8EQVi5jkZeW9PWUAjpUGfa9WwhkS86LZ4_uo4xwPvnooSmWPLx9qgK1N9-4Uo7g-OaOppzz_VGaz2G6HjYVMfWkPAVsbmyVq4RR28bcwQT1wFF6Nr1j0BFUNC7Me9xqqmXG1SmKgZUnsDlUMJE_4EJOduse3-EQcCV6MTVHo9wcQi761WbA_oUbtj-n7LXKVg6GM3dtqqq0QvUpaoMabkVVvfX13hrbYbEXCK0wy1yi-mdAVgPGJgFW9J5K0wHEub0Jcd_Mb147AmcZn_JKp5MmCFk7tA.YLmyzZfvUFGwdnv1xAXFhw.NovRBZAEU6uaLbbEurvBtvmComFOy_MZZArtaLW16lw4FDyF9aGti-vgoFxByUCdymSId_LMFiDjcjP0RIaTTpbgQbPrb3-Ib3Tvp4Zl5uENHckeocQeVQEXroLzQqNgAeXwIH3AEfGpCPt5Qq6k1vzxRLBX4VvNjbwk1I0aB6lELxKDtkvxnJTktaT1kuRAE5zabRh0P5xu4kmPf9-tqVv_0zm7KnXAPzImkbqRTG2C9HqDEBZVkyXiQRUjeo2mAHAW4spWxulCEilndG-OJ2MN6yRdN_0cEnTOkHKBh8FgN0iEIdPSNl1-wRGoC8G_EfCJNivqnTqOdH_wkPm0FDsL2XId8QSdL_3adHeEQ5QP6bzjPBHZ-AN0GWsfhIkCL94YsFRG3AkqOpiuzhZJpQDAWBdkqbWSVfxk0keFm9btUj6jWuIZ8MdB4yQpyB1KsKq80A0c_L8GV5DpLJ7A-M9kw-bmDZskm2Q59WOx9ymZgaYxVjbq6GMjjBsDhSqxHtUjSXq68LxpJ-ytw_2lR6oCY6ZHkg2PazMvNYdsXZohPd6FJVt0XEjKrwzQaBwV-m_9zYTpbLOBp9bftVkV6_0IRV0fJwooIZMfBtiCMraDZBNI8pvU-_U2II5IOX3oPFTZdDjv9ZHCmzafNSp_WmHawJc9xoAQ3B-fNdNzsDEUU7HLUZkBjlgmRyO6sNpYS1oBUBVZJwAXxW77zelCk6GhkjVkepHc5WAL7aeJ5z8Z_bllxMAFFoY6o0F70CMxCc08LAER81QOatOiqZlBxdFmwG83D7TMycTfrfAykeseoZlgMLxw6mWxar1XArUBBf1MzLbikzd_Z4YjfenjUMMrqQuPkeAIieOxasrGw8Y4JYWaY0GOBRQqd9HaibwnUAK8HS5d3bE9XrqBhkLyC3HpDE9s_SWQavCNQ9QB6146cnULLd6noE_HPz_ppQhR7biUngFDh226GnfyaA_DKuKJfdkBMS62IXF8f70sm-c.4QI1W1LB_la5b-UpwjUnnQ"
  }
  
}